pipeline {
  agent { label 'dentalagent' }

  environment {
    AWS_REGION      = "us-east-2"
    TF_DIR          = "terraform"
    AWS_CREDENTIALS = credentials('aws-credentials')
    AWS_SESSION_TOKEN = credentials('aws-session-token')
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Terraform Init & Validate') {
      steps {
        dir("${env.TF_DIR}") {
          sh 'terraform init'
          sh 'terraform validate'
        }
      }
    }

    stage('Terraform Plan') {
      steps {
        dir("${env.TF_DIR}") {
          sh 'terraform plan -out=tfplan'
        }
      }
    }

    stage('Terraform Apply') {
      steps {
        input message: '¿Aprobar despliegue?', ok: 'Desplegar'
        dir("${env.TF_DIR}") {
          sh 'terraform apply -auto-approve tfplan'
        }
      }
    }
  }
}
