name: Terraform Pipeline

on:
  # Ejecutar Plan automáticamente al hacer push a develop
  push:
    branches: [ "develop" ]
  # Botón manual para desplegar (Plan + Apply)
  workflow_dispatch:
    inputs:
      action:
        description: 'Acción a realizar'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    # Usar bash shell
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    # 1. Checkout del código
    - name: Checkout
      uses: actions/checkout@v4

    # 2. Configurar AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-2

    # 3. Instalar Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.2

    # 4. Terraform Init
    - name: Terraform Init
      run: terraform init

    # 5. Terraform Validate
    - name: Terraform Validate
      run: terraform validate

    # 6. Terraform Plan
    - name: Terraform Plan
      run: terraform plan -var-file=staging.terraform.tfvars -out=tfplan

    # 7. Terraform Apply (Solo si es manual y se seleccionó 'apply')
    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch' && inputs.action == 'apply'
      run: terraform apply -auto-approve tfplan
